#!/bin/bash
# COLOR VALIDATION
clear
y='\033[1;33m' #yellow
BGX="\033[42m"
CYAN="\033[0;36m"
z="\033[95;1m"
f="\033[1;97;41m"
G="\033[92m"
RED='\033[0;31m'
NC='\033[0;34m'
gray="\e[1;30m"
Blue="\033[0;34m"
green='\033[0;32m'
grenbo="\e[92;1m"
purple="\033[1;95m"
YELL='\033[0;32m'
p='\033[0;37m'
clear
# underline
UPU='\033[5;35m'
UCY='\033[5;36m'
UWH='\033[5;37m'
IPVPS=$(curl -s ipv4.icanhazip.com)
domain=$(cat /etc/xray/domain)
LOADCPU=$(printf '%-0.00001s' "$(top -bn1 | awk '/Cpu/ { cpu = "" 100 - $8 "%" }; END { print cpu }')")
MODEL=$(cat /etc/os-release | grep -w PRETTY_NAME | head -n1 | sed 's/=//g' | sed 's/"//g' | sed 's/PRETTY_NAME//g')
#CORE=$(printf '%-1s' "$(grep -c cpu[0-9] /proc/stat)")
DATEVPS=$(date +'%d-%m-%Y')
TIMEZONE=$(printf '%(%H-%M-%S)T')
SERONLINE=$(uptime -p | cut -d " " -f 2-10000)
clear
MYIP=$(curl -sS ipv4.icanhazip.com)
echo ""
clear
clear

# OS Uptime
uptime="$(uptime -p | cut -d " " -f 2-10)"

# Getting CPU Information
cpu_usage1="$(ps aux | awk 'BEGIN {sum=0} {sum+=$3}; END {print sum}')"
cpu_usage="$((${cpu_usage1/\.*} / ${coREDiilik:-1}))"
cpu_usage+=" %"
WKT=$(curl -s ipinfo.io/timezone )
DAY=$(date +%A)
DATE=$(date +%m/%d/%Y)
DATE2=$(date -R | cut -d " " -f -5)
cname=$( awk -F: '/model name/ {name=$2} END {print name}' /proc/cpuinfo )
cores=$( awk -F: '/model name/ {core++} END {print core}' /proc/cpuinfo )
freq=$( awk -F: ' /cpu MHz/ {freq=$2} END {print freq}' /proc/cpuinfo )
tram=$( free -m | awk 'NR==2 {print $2}' )
uram=$( free -m | awk 'NR==2 {print $3}' )
fram=$( free -m | awk 'NR==2 {print $4}' )
clear
ssh_service=$(/etc/init.d/ssh status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
dropbear_service=$(/etc/init.d/dropbear status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
haproxy_service=$(systemctl status haproxy | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
xray_service=$(systemctl status xray | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
nginx_service=$(systemctl status nginx | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
#Status
clear
# STATUS SERVICE  SSH 
if [[ $ssh_service == "running" ]]; then 
   status_ssh="${green}ON"
else
   status_ssh="${RED}ERROR"
fi

# // SSH Websocket Proxy
ssh_ws=$( systemctl status ws | grep Active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g' )
if [[ $ssh_ws == "running" ]]; then
    status_ws_epro="${green}ON"
else
    status_ws_epro="${RED}ERROR"
fi

# STATUS SERVICE HAPROXY
if [[ $haproxy_service == "running" ]]; then 
   status_haproxy="${green}ON"
else
   status_haproxy="${RED}ERROR"
fi

# STATUS SERVICE XRAY
if [[ $xray_service == "running" ]]; then 
   status_xray="${green}ON"
else
   status_xray="${RED}ERROR"
fi

# STATUS SERVICE NGINX
if [[ $nginx_service == "running" ]]; then 
   status_nginx="${green}ON"
else
   status_nginx="${RED}ERROR"
fi

# STATUS SERVICE Dropbear
if [[ $dropbear_service == "running" ]]; then 
   status_dropbear="${green}ON"
else
   status_dropbear="${RED}ERROR"
fi
# //
# // Log account
vlx=$(grep -c -E "^#& " "/etc/xray/config.json")
let vla=$vlx/2
vmc=$(grep -c -E "^### " "/etc/xray/config.json")
let vma=$vmc/2
ssh1="$(awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd | wc -l)"
trx=$(grep -c -E "^#! " "/etc/xray/config.json")
let trb=$trx/2
ssx=$(grep -c -E "^#ss# " "/etc/xray/config.json")
let ssa=$ssx/2
# //
r="\033[1;31m"  # merah
a="ACCOUNT" 
BWC='\033[1;36'
cyan='\033[96m'
bwhite='\033[1;37m'
clear
echo -e " "                                                           
echo -e " ${NC} ╭════════════════════════════════════════════════════════════╮"
echo -e " ${NC} │\033[0;37m               Welcome To Script Premium FZVPN           ${NC}"
echo -e " ${NC} ╰════════════════════════════════════════════════════════════╯"
echo -e " ${NC} ╭════════════════════════════════════════════════════════════╮"
echo -e " ${NC} │$RED ● ${CYAN}SYSTEM OS ${YELL}   = \033[0;37m$MODEL${NC}"
echo -e " ${NC} │$RED ● ${CYAN}SERVER RAM ${YELL}  = \033[0;37m$tram / $uram MB $NC"
echo -e " ${NC} │$RED ● ${CYAN}LOADCPU ${YELL}     = \033[0;37m$LOADCPU $NC"
echo -e " ${NC} │$RED ● ${CYAN}DATE ${YELL}        = \033[0;37m$DATEVPS${NC}"
echo -e " ${NC} │$RED ● ${CYAN}TIME ${YELL}        = \033[0;37m$TIMEZONE${NC}"
echo -e " ${NC} │$RED ● ${CYAN}UPTIME ${YELL}      = \033[0;37m$SERONLINE${NC}"
echo -e " ${NC} │$RED ● ${CYAN}IP VPS ${YELL}      = \033[0;37m$IPVPS${NC}"
echo -e " ${NC} │$RED ● ${CYAN}DOMAIN ${YELL}      = \033[0;37m$domain${NC}"
echo -e " ${NC} ╰════════════════════════════════════════════════════════════╯$NC"
echo -e " \033[0;37m                  >>> INFORMATION ACCOUNT <<< "
echo -e " ${NC}         ═════════════════════════════════════════════${NC}" 
echo -e "               \033[0;32m SSH/OPENVPN/UDP  $YELL=\033[0;37m $ssh1  ${YELL}$a"
echo -e "               ${BRED} VMESS/WS/GRPC    $YELL=\033[0;37m $vma  ${YELL}$a"
echo -e "               ${BRED} VLESS/WS/GRPC    $YELL=\033[0;37m $vla  ${YELL}$a"
echo -e "               ${BRED} TROJAN/WS/GRPC   $YELL=\033[0;37m $trb  ${YELL}$a"
echo -e "               ${BRED} SHADOW/WS/GRPC   $YELL=\033[0;37m $ssa  ${YELL}$a"
echo -e " ${NC}         ═════════════════════════════════════════════${NC}" 
echo -e " \033[0;37m              >>> Info wa +62 821-3031-9036 <<<"
echo -e " ${NC} ╭═══════════════════╮╭═══════════════════╮╭══════════════════╮$NC"
echo -e " ${NC} │\033[0;33m SSH     $status_ssh           \033[0;33m NGINX $status_nginx             \033[0;33m HAPROXY  $status_haproxy    ${NC}"
echo -e " ${NC} │\033[0;33m WS-ePro $status_ws_epro           \033[0;33m XRAY  $status_xray             \033[0;33m DROPBEAR $status_dropbear    ${NC}"
echo -e " ${NC} ╰═══════════════════╯╰═══════════════════╯╰══════════════════╯$NC"
echo -e " ${NC} ╭════════════════════════════════════════════════════════════╮"
echo -e " ${NC} │$NC [${CYAN}01$NC]${YELL} SSH MENU     $NC│ [${CYAN}08$NC]${YELL} BCKP/RSTR     $NC│ [${CYAN}15$NC]${YELL} MENU BOT ${NC}"
echo -e " ${NC} │$NC [${CYAN}02$NC]${YELL} VMESS MENU   $NC│ [${CYAN}09$NC]${YELL} GOTOP X RAM   $NC│ [${CYAN}16$NC]${YELL} CHANGE DOMAN ${NC}"    
echo -e " ${NC} │$NC [${CYAN}03$NC]${YELL} VLESS MENU   $NC│ [${CYAN}10$NC]${YELL} RESTART ALL   $NC│ [${CYAN}17$NC]${YELL} FIX CRT DOMAN${NC}"  
echo -e " ${NC} │$NC [${CYAN}04$NC]${YELL} TROJAN MENU  $NC│ [${CYAN}11$NC]${YELL} TELE BOT      $NC│ [${CYAN}18$NC]${YELL} CANGE BANNER ${NC}"
echo -e " ${NC} │$NC [${CYAN}05$NC]${YELL} AKUN NOOBZVPN$NC│ [${CYAN}12$NC]${YELL} UPDATE SCRIPT $NC│ [${CYAN}19$NC]${YELL} RESTART BANNER${NC}"
echo -e " ${NC} │$NC [${CYAN}06$NC]${YELL} SS - LIBEV  $NC │ [${CYAN}13$NC]${YELL} RUNNING       $NC│ [${CYAN}20$NC]${YELL} SPEEDTEST    ${NC}"
echo -e " ${NC} │$NC [${CYAN}07$NC]${YELL} INSTALL UDP  $NC│ [${CYAN}14$NC]${YELL} INFO PORT$NC     │ [${CYAN}21$NC]${YELL} EKSTRAK MENU    ${NC}"
echo -e " ${NC} ╰════════════════════════════════════════════════════════════╯"
echo -e " ${NC} ╭════════════════════════════════════════════════════════════╮"
echo -e " ${NC} │\033[0;37m Script Version $YELL=\033[0;31m V \033[0;37mGRATIS 2024 "
echo -e " ${NC} ╰════════════════════════════════════════════════════════════╯\033[0;37m"
echo -e " "
read -p "  Options [ 1 - 18 ] ❱❱❱ " opt
echo -e ""
case $opt in
1 | 01)
clear
m-sshws
;;
2 | 02)
clear
m-vmess
;;
3 | 03)
clear
m-vless
;;
4 | 04)
clear
m-trojan
;;
5 | 05)
clear
m-noob
;;
6 | 06)
clear
m-ssws
;;
7 | 07)
clear
udepe
;;
8 | 08)
clear
menu-backup
;;
9 | 09)
clear
gotop
;;
10)
clear
restart
;;
11)
clear
m-bot
;;
12)
clear
wget -q https://raw.githubusercontent.com/Arya-Blitar22/oying/main/update.sh
chmod +x update.sh
./update.sh
;;
13)
clear
run
;;
14)
clear
prot
;;
15)
clear
mbot-panel
;;
16)
clear
addhost
;;
17)
clear
fixcert
;;
18)
clear
nano /etc/kyt.txt
;;
19)
clear
/etc/init.d/dropbear restart
;;
20)
clear
speedtest
;;
21)
clear
m-system
;;
0 | 00)
exit
;;
x)
menu
;;
*) clear ;
menu
;;
esac